obj-m := plc_ldisc.o act_plc.o motor_driver.o merlin_driver.o
plc_ldisc-y := plc_ldisc/plc_ldisc.o
act_plc-y := act_plc/act_plc.o
merlin_driver-y := merlin_driver/merlin_driver.o
motor_driver-y := motor_driver/motor_intfce.o motor_driver/motor_driver.o
ccflags-y := -I$(src)/
